### ISSUE TITLE
Hot reload cannot work

### ISSUE THREAD

**Issue by kairyou** [hung-phan/koa-react-isomorphic#10]
Hi,

Run `npm run watch` and `npm run dev`, and modified the `/todos/todos-body/style.css`(added `color:red`).
But, the hot reload cannot work, need to do a full reload.

![image](https://cloud.githubusercontent.com/assets/544524/13066724/c9643dc6-d4a3-11e5-8c04-c0e29b5bff22.png)

![image](https://cloud.githubusercontent.com/assets/544524/13066673/7b29b99c-d4a3-11e5-91ca-b9cd849b7b64.png)

---------
After a full reload:
![image](https://cloud.githubusercontent.com/assets/544524/13066719/bf9e8800-d4a3-11e5-9d7e-dc4b088da486.png)

**Comment by hung-phan** [comment]
This will fix @kairyou. The problem is current version of webpack dev

**Comment by kairyou** [comment]
Thanks! :+1:
