### ISSUE TITLE
Bug with multi router when SERVER_RENDERING=true

### ISSUE THREAD

**Issue by kairyou** [hung-phan/koa-react-isomorphic#20]
```js
// app/routes.js
// ...
<Route path='/' component={ Todos } />
<Route path='/test' component={ Test } />
```

```sh
SERVER_RENDERING=true npm run watch
npm run dev
```
`http://localhost:3000/test` always auto redirect to '/'.

**Comment by hung-phan** [comment]
Checking

**Comment by hung-phan** [comment]
@kairyou Can you check again with this commit?

**Comment by hung-phan** [comment]
This is the reason `https://github.com/hung-phan/koa-react-isomorphic/commit/2ac5c79c0208da6f33025fe914c68bc4010732d9#diff-6db976b763ed71154781e45807c0d4e5R15`

**Comment by kairyou** [comment]
It works normally now. Thanks :)
