### ISSUE TITLE
NPM installation failing

### ISSUE THREAD

**Issue by margaretmoser** [hung-phan/koa-react-isomorphic#29]
In a new, clean directory, npm i koa-react-isomorphic results in the following:

```
scripts/postinstall: line 1: [: =: unary operator expected
[...]/projects/koa-react-iso/inner
└─┬ koa-react-isomorphic@2.1.1
  ├── UNMET PEER DEPENDENCY eslint@3.0.0
  ├─┬ pm2@1.1.3
  │ └── ikt@0.0.0  (git+http://ikt.pm2.io/ikt.git#3325a3e39a502418dc2e2e4bf21529cbbde96228)
  └── UNMET PEER DEPENDENCY webpack@2.1.0-beta.15

npm WARN enoent ENOENT: no such file or directory, open '/Users/margaret.moser/Documents/projects/koa-react-iso/inner/package.json'
npm WARN chunk-manifest-webpack-plugin@0.1.0 requires a peer of webpack@^1.4.0-beta6 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none was installed.
npm WARN extract-text-webpack-plugin@1.0.1 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN purifycss-webpack-plugin@2.0.3 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN webpack-dev-server@2.0.0-beta requires a peer of webpack@>=2.0.3-beta <3 but none was installed.
```

(Note, it's not complaining about parent directories anymore – that seems to have resolved after I deleted some files from parent directories.) The node_modules folder is created but no other koa-react-isomorphic files are present, including the package.json.

I don't think the unmet-peer messages are the root of the problem, but I do have webpack@2.1.0-beta.15 and eslint@3.0.0 installed globally. I think I'm still getting the messages because of https://github.com/npm/npm/issues/9857, but that doesn't explain why I'm not getting the rest of the files.

Not sure what's going on. I'll try installing from a git clone next and see what happens.

**Comment by margaretmoser** [comment]
```
git clone https://github.com/hung-phan/koa-react-isomorphic.git
cd koa-react-isomorphic/
npm i
npm run dev
```
I get similar warnings from the npm i about webpack and eslint, but no errors. npm start and npm run dev both result in an endless loop of
`[webpack-isomorphic-tools] (waiting for the first Webpack build to finish)`

**Comment by hung-phan** [comment]
You forgot to run `npm run watch` before `npm run dev`

**Comment by hung-phan** [comment]
https://github.com/hung-phan/koa-react-isomorphic#hot-reload. @margaretmoser . Can you try again?

**Comment by hung-phan** [comment]
I mean these two are separated commands. You need to run both of them in different screens.
<img width="1280" alt="screen shot 2016-07-06 at 8 11 37 am" src="https://cloud.githubusercontent.com/assets/3093244/16604618/51bc8522-4351-11e6-945b-ce7f0c765e79.png">

**Comment by hung-phan** [comment]
By the way, you don't need eslint and webpack installed globally. It's only warning for peer dependencies.

**Comment by kairyou** [comment]
@hung-phan 
The `[ $NODE_ENV = "production" ]` should change to `[[ $NODE_ENV = "production" ]]`
for fix  throw error `scripts/postinstall: line 1: [: =: unary operator expected` when NODE_ENV is null.

[http://stackoverflow.com/a/15573770](http://stackoverflow.com/a/15573770)

**Comment by hung-phan** [comment]
oh, Thanks @kairyou

**Comment by hung-phan** [comment]
https://github.com/hung-phan/koa-react-isomorphic/commit/160c922d7784c7554538a2fecb08c8326a9f0a05
